import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import { ToastProvider } from "@/components/ui/toast";

import "./globals.css";

const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Toasts outlive route changes, so the provider sits above every page instead of inside one. */}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
